
export const COLORS = {
  ACCENT: '#ffffff',
  DEEP_BLACK: '#000000',
  TEXT_WHITE: '#FFFFFF',
  TEXT_GRAY: '#666666',
};

export const TRANSLATIONS = {
  ro: {
    MISSION: 'Transformăm securitatea complexă într-un standard silențios pentru viața digitală de zi cu zi.',
    HERO_SLOGAN_1: 'Securitate prin',
    HERO_SLOGAN_2: 'Implicit',
    HERO_SLOGAN_3: 'Confidențialitate ca',
    HERO_SLOGAN_4: 'Standard',
    HERO_DESC: 'Redobândește accesul la datele tale prin criptare pe partea clientului și zero-knowledge.',
    BTN_ACCESS: 'Despre Noi',
    BTN_DOCS: 'Documentație',
    THE_STANDARD: 'Standardul',
    PACT_TITLE: 'Protocol 3305: Un Pact Pentru Demnitate.',
    PREAMBLE_LABEL: 'Preambul',
    PREAMBLE_TEXT: 'Într-o eră în care datele personale au devenit cea mai valoroasă marfă, a apărut o paradigmă periculoasă: capitalismul de supraveghere. Software-ul mainstream, oferit adesea „gratuit”, este proiectat pentru a monitoriza, analiza și monetiza exact persoanele pe care pretinde că le servește. Această paradigmă erodează demnitatea digitală, compromite securitatea personală și creează un dezechilibru de putere inacceptabil între corporații și indivizi.',
    PROTOCOL_DESC: 'Protocolul 3305 este un standard deschis și nenegociabil, conceput pentru a demonta această paradigmă. Acesta oferă un set de principii auditabile și verificabile tehnic pentru orice organizație angajată în protejarea persoanei din spatele ecranului.',
    ADHERENCE: 'Aderarea la acest protocol confirmă faptul că un serviciu este structural incapabil să își exploateze oamenii, fiind construit pe o fundație de tip zero-knowledge și zero-trust.',
    FOOTER_MISSION: 'Suntem aici să facem intimitatea standard.',
    APPS_SECTION_TITLE: 'Proiecte',
    APPS: [
      { id: '01', title: 'CrytoTool', tagline: 'Seif Digital', desc: 'All-in-One Privacy, manager de fișiere cu criptare client-side, galerie, player muzical și vizualizator de documente unde confidențialitatea ta vine pe primul loc.', logoImage: '/CrytoTool.png', features: ['4 în 1', 'Multiplatform: Windows, Linux, macOS și Android', '6 Algoritmi de Criptare', '52 de Limbi', '100 de Teme'] },
    ],
    NAV: {
      HOME: 'Acasă',
      PROTOCOL: 'Protocol',
      PHILOSOPHY: 'Filozofie',
      VISION: 'Viziune',
      VAULT: 'Aplicații',
      INFRA: 'Infrastructură',
      ETHICS: 'Etică',
      ABOUT: 'Despre Noi',
      CONTACT: 'Contact',
      MENU: 'Meniu'
    },
    ANDROID_TITLE: 'Menținem Android Deschis: Luptă Împotriva Închiderii.',
    ANDROID_LABEL: 'Context',
    ANDROID_PREAMBLE: 'Începând cu septembrie 2026, Google va impune ca fiecare aplicație Android să fie înregistrată de un dezvoltator verificat. Această verificare necesită plata unei taxe, predarea unui act de identitate guvernamental, dovada cheilor private de semnare și listarea tuturor aplicațiilor. Aceasta nu este o măsură de securitate — este o închidere a ecosistemului deschis care a definit Android de la început.',
    ANDROID_CARD_TEXT: 'La Privon Foundation, credem că dreptul de a instala software pe un dispozitiv pe care l-ai cumpărat este fundamental. Ne angajăm să luptăm împotriva acestei mișcări și să facem vocea comunității auzită. Nu vom sta cu brațele încrucișate în timp ce o corporație închide o platformă construită pe promisiunea libertății.',
    ANDROID_ARTICLES: [
      { id: 'STEP 01', title: 'Instalează F-Droid', desc: 'Alternativele supraviețuiesc doar dacă oamenii le folosesc. Instalează F-Droid pe fiecare dispozitiv Android pe care îl deții.', pilar: 'Acțiune', status: 'Essential' },
      { id: 'STEP 02', title: 'Semnează Petiția', desc: 'Peste 100.000 de semnatari s-au alăturat deja. Fă-ți vocea auzită pe change.org și oprește această mișcare.', pilar: 'Acțiune', status: 'Essential' },
      { id: 'STEP 03', title: 'Distribuie Mesajul', desc: 'Link către keepandroidopen.org peste tot. Nu lăsa narativa să fie setată de alții. Fiecare persoană informată contează.', pilar: 'Comunitate', status: 'Ongoing' },
      { id: 'STEP 04', title: 'Contactează Regulatorii', desc: 'Regulatorii din întreaga lume sunt preocupați de monopoluri și centralizare. Vor să audă direct de la persoanele afectate.', pilar: 'Comunitate', status: 'Ongoing' },
    ],
    ANDROID_LINKS: [
      { label: 'Keep Android Open', url: 'https://keepandroidopen.org' },
      { label: 'Open Letter (F-Droid)', url: 'https://f-droid.org/en/2026/02/24/open-letter-opposing-developer-verification.html' },
      { label: 'Change.org Petition', url: 'https://www.change.org/p/stop-google-from-limiting-apk-file-usage/' },
    ],
  },
  en: {
    MISSION: 'Transforming complex security into a silent standard for everyday digital life.',
    HERO_SLOGAN_1: 'Security By',
    HERO_SLOGAN_2: 'Default',
    HERO_SLOGAN_3: 'Privacy As',
    HERO_SLOGAN_4: 'Standard',
    HERO_DESC: 'Reclaim access to your data through client-side encryption and zero-knowledge.',
    BTN_ACCESS: 'Secure Access',
    BTN_DOCS: 'Documentation',
    THE_STANDARD: 'The Standard',
    PACT_TITLE: 'Protocol 3305: A Pact For Dignity.',
    PREAMBLE_LABEL: 'Preamble',
    PREAMBLE_TEXT: 'In an era where personal data has become the most valuable commodity, a dangerous paradigm has emerged: surveillance capitalism. Mainstream software, often offered for "free," is architected to monitor, analyze, and monetize the very people it claims to serve. This paradigm erodes digital dignity and compromises personal security.',
    PROTOCOL_DESC: 'Protocol 3305 is an open, non-negotiable standard designed to dismantle this paradigm. It provides a set of auditable, technically verifiable principles for any organization committed to building software that respects the person behind the screen.',
    ADHERENCE: 'Adherence to this protocol signifies that a service is structurally incapable of exploiting its people, because it is built on a foundation of zero-knowledge and zero-trust.',
    FOOTER_MISSION: 'We are here to make privacy the standard.',
    APPS_SECTION_TITLE: 'Projects',
    APPS: [
      { id: '01', title: 'CrytoTool', tagline: 'Digital Vault', desc: 'All-in-One Privacy, client-side encryption file manager, gallery, music player, and document viewer where your privacy comes first.', logoImage: '/CrytoTool.png', features: ['4 in 1', 'Multiplatform: Windows, Linux, macOS & Android', '6 Encryption Algorithms', '52 Languages', '100 Themes'] },
    ],
    NAV: {
      HOME: 'Home',
      PROTOCOL: 'Protocol',
      PHILOSOPHY: 'Philosophy',
      VISION: 'Vision',
      VAULT: 'Apps',
      INFRA: 'Infrastructure',
      ETHICS: 'Ethics',
      ABOUT: 'About Us',
      CONTACT: 'Contact',
      MENU: 'Menu'
    },
    ANDROID_TITLE: 'Keep Android Open: Fight The Lockdown.',
    ANDROID_LABEL: 'Context',
    ANDROID_PREAMBLE: 'Starting September 2026, Google will require every Android app to be registered by a verified developer. This verification requires paying a fee, surrendering government ID, providing evidence of private signing keys, and listing all applications. This is not a security measure — it is a lockdown of the open ecosystem that has defined Android from the start.',
    ANDROID_CARD_TEXT: 'At Privon Foundation, we believe the right to install software on a device you purchased is fundamental. We commit to fighting this move and making the community\'s voice heard. We will not stand idly by while a corporation closes a platform built on the promise of freedom.',
    ANDROID_ARTICLES: [
      { id: 'STEP 01', title: 'Install F-Droid', desc: 'Alternatives only survive if people actually use them. Install F-Droid on every Android device you own.', pilar: 'Action', status: 'Essential' },
      { id: 'STEP 02', title: 'Sign the Petition', desc: 'Over 100,000 signatories have already joined. Make your voice heard on change.org and stop this movement.', pilar: 'Action', status: 'Essential' },
      { id: 'STEP 03', title: 'Spread the Word', desc: 'Link to keepandroidopen.org everywhere. Don\'t let others set the narrative. Every informed person matters.', pilar: 'Community', status: 'Ongoing' },
      { id: 'STEP 04', title: 'Contact Regulators', desc: 'Regulators worldwide are concerned about monopolies and centralization. They want to hear directly from affected individuals.', pilar: 'Community', status: 'Ongoing' },
    ],
    ANDROID_LINKS: [
      { label: 'Keep Android Open', url: 'https://keepandroidopen.org' },
      { label: 'Open Letter (F-Droid)', url: 'https://f-droid.org/en/2026/02/24/open-letter-opposing-developer-verification.html' },
      { label: 'Change.org Petition', url: 'https://www.change.org/p/stop-google-from-limiting-apk-file-usage/' },
    ],
  },
  es: {
    MISSION: 'Transformando la seguridad compleja en un estándar silencioso para la vida digital cotidiana.',
    HERO_SLOGAN_1: 'Seguridad Por',
    HERO_SLOGAN_2: 'Defecto',
    HERO_SLOGAN_3: 'Privacidad Como',
    HERO_SLOGAN_4: 'Estándar',
    HERO_DESC: 'Recupera el acceso a tus datos mediante cifrado del lado del cliente y zero-knowledge.',
    THE_STANDARD: 'El Estándar',
    PACT_TITLE: 'Protocolo 3305: Un Pacto Por La Dignidad.',
    PREAMBLE_LABEL: 'Preámbulo',
    PREAMBLE_TEXT: 'En una era en la que los datos personales se han convertido en la mercancía más valiosa, ha surgido un paradigma peligroso: el capitalismo de vigilancia. El software convencional, a menudo ofrecido "gratis", está diseñado para monitorear, analizar y monetizar a las mismas personas que dice servir. Este paradigma erosiona la dignidad digital y compromete la seguridad personal.',
    PROTOCOL_DESC: 'El Protocolo 3305 es un estándar abierto e innegociable diseñado para desmantelar este paradigma. Proporciona un conjunto de principios auditables y técnicamente verificables para cualquier organización comprometida con construir software que respete a la persona detrás de la pantalla.',
    ADHERENCE: 'La adhesión a este protocolo significa que un servicio es estructuralmente incapaz de explotar a sus personas, porque está construido sobre una base de zero-knowledge y zero-trust.',
    FOOTER_MISSION: 'Estamos aquí para hacer de la privacidad un estándar.',
    APPS_SECTION_TITLE: 'Proyectos',
    APPS: [
      { id: '01', title: 'CrytoTool', tagline: 'Bóveda Digital', desc: 'All-in-One Privacy, administrador de archivos con cifrado client-side, galería, reproductor de música y visor de documentos donde tu privacidad es lo primero.', logoImage: '/CrytoTool.png', features: ['4 en 1', 'Multiplataforma: Windows, Linux, macOS y Android', '6 Algoritmos de Cifrado', '52 Idiomas', '100 Temas'] },
    ],
    NAV: {
      HOME: 'Inicio',
      PROTOCOL: 'Protocolo',
      PHILOSOPHY: 'Filosofía',
      VISION: 'Visión',
      VAULT: 'Apps',
      INFRA: 'Infraestructura',
      ETHICS: 'Ética',
      ABOUT: 'Sobre Nosotros',
      CONTACT: 'Contacto',
      MENU: 'Menú'
    },
    ANDROID_TITLE: 'Mantén Android Abierto: Lucha Contra El Cierre.',
    ANDROID_LABEL: 'Contexto',
    ANDROID_PREAMBLE: 'A partir de septiembre de 2026, Google exigirá que cada app de Android sea registrada por un desarrollador verificado. Esta verificación requiere pagar una tarifa, entregar un documento de identidad gubernamental, proporcionar evidencia de claves privadas de firma y listar todas las aplicaciones. Esto no es una medida de seguridad — es un cierre del ecosistema abierto que ha definido a Android desde el inicio.',
    ANDROID_CARD_TEXT: 'En Privon Foundation, creemos que el derecho de instalar software en un dispositivo que compraste es fundamental. Nos comprometemos a luchar contra esta medida y hacer que la voz de la comunidad se escuche. No nos quedaremos de brazos cruzados mientras una corporación cierra una plataforma construida sobre la promesa de libertad.',
    ANDROID_ARTICLES: [
      { id: 'STEP 01', title: 'Instala F-Droid', desc: 'Las alternativas solo sobreviven si la gente las usa. Instala F-Droid en cada dispositivo Android que poseas.', pilar: 'Acción', status: 'Essential' },
      { id: 'STEP 02', title: 'Firma la Petición', desc: 'Más de 100.000 firmantes ya se han unido. Haz que tu voz se escuche en change.org y detén este movimiento.', pilar: 'Acción', status: 'Essential' },
      { id: 'STEP 03', title: 'Difunde el Mensaje', desc: 'Enlaza keepandroidopen.org en todas partes. No dejes que otros establezcan la narrativa. Cada persona informada cuenta.', pilar: 'Comunidad', status: 'Ongoing' },
      { id: 'STEP 04', title: 'Contacta a los Reguladores', desc: 'Los reguladores en todo el mundo están preocupados por los monopolios y la centralización. Quieren escuchar directamente de las personas afectadas.', pilar: 'Comunidad', status: 'Ongoing' },
    ],
    ANDROID_LINKS: [
      { label: 'Keep Android Open', url: 'https://keepandroidopen.org' },
      { label: 'Carta Abierta (F-Droid)', url: 'https://f-droid.org/en/2026/02/24/open-letter-opposing-developer-verification.html' },
      { label: 'Petición Change.org', url: 'https://www.change.org/p/stop-google-from-limiting-apk-file-usage/' },
    ],
  }
};

export const PROTOCOL_ARTICLES = {
  ro: [
    { id: 'ART 00', title: 'Monetizare Etică', desc: 'Monetizarea datelor personale este strict interzisă. Modelele de business trebuie decuplate de supraveghere.', pilar: 'Etică', status: 'Core Logic' },
    { id: 'ART 01', title: 'Privacy by Design', desc: 'Confidențialitatea este integrată în arhitectura fundamentală pentru a minimiza colectarea datelor de la zero.', pilar: 'Arhitectură', status: 'Mandatory' },
    { id: 'ART 02', title: 'Security by Default', desc: 'Cele mai înalte setări de securitate sunt activate implicit. Siguranța este starea standard.', pilar: 'Arhitectură', status: 'Mandatory' },
    { id: 'ART 03', title: 'Zero Trust', desc: 'Niciodată nu ai încredere, întotdeauna verifici. Accesul este acordat granular și validat continuu.', pilar: 'Arhitectură', status: 'Activ' },
    { id: 'ART 04', title: 'Zero Knowledge', desc: 'E2EE este obligatoriu. Furnizorii trebuie să fie structural incapabili să citească conținutul oamenilor.', pilar: 'Suveranitate', status: 'Enforced' },
    { id: 'ART 05', title: 'Zero Date Personale', desc: 'Fără date PII stocate dincolo de funcționalitatea absolută. Sistemele nu pot profila oamenii.', pilar: 'Suveranitate', status: 'Enforced' },
    { id: 'ART 06', title: 'Zero Jurnale de Activitate', desc: 'Fără log-uri de activitate, adrese IP sau metadate folosite pentru a urmări comportamentul.', pilar: 'Suveranitate', status: 'Enforced' },
    { id: 'ART 07', title: 'Open Source', desc: 'Transparența înseamnă încredere. Tot codul trebuie să fie deschis pentru audit public.', pilar: 'Integritate', status: 'Public Audit' },
    { id: 'ART 08', title: 'Privilegiu Minim', desc: 'Sunt solicitate doar permisiunile esențiale. Fără posibilitatea de abuz prin acces nenecesar.', pilar: 'Integritate', status: 'Active' },
  ],
  en: [
    { id: 'ART 00', title: 'Ethical Monetization', desc: 'The monetization of personal data is strictly forbidden. Business models must be decoupled from surveillance.', pilar: 'Ethics', status: 'Core Logic' },
    { id: 'ART 01', title: 'Privacy by Design', desc: 'Privacy integrated into the fundamental architecture to minimize data collection from ground zero.', pilar: 'Architecture', status: 'Mandatory' },
    { id: 'ART 02', title: 'Security by Default', desc: 'Highest security settings enabled by default. Safety is the standard state, not a user option.', pilar: 'Architecture', status: 'Mandatory' },
    { id: 'ART 03', title: 'Zero Trust', desc: 'Never trust, always verify. Access is granted granularly and continuously validated.', pilar: 'Architecture', status: 'Active' },
    { id: 'ART 04', title: 'Zero Knowledge', desc: 'E2EE is mandatory. Service providers must be structurally unable to read person-generated content.', pilar: 'Sovereignty', status: 'Enforced' },
    { id: 'ART 05', title: 'Zero Personal Data', desc: 'No PII stored beyond absolute functionality. Systems cannot possess info that profiles people.', pilar: 'Sovereignty', status: 'Enforced' },
    { id: 'ART 06', title: 'Zero Activity Logs', desc: 'No logs of activity, IP addresses, or metadata used to track behavior or session times.', pilar: 'Sovereignty', status: 'Enforced' },
    { id: 'ART 07', title: 'Open Source', desc: 'Transparency is trust. All code must be open for public audit and global community validation.', pilar: 'Integrity', status: 'Public Audit' },
    { id: 'ART 08', title: 'Least Privilege', desc: 'Only essential permissions requested. No possibility of abuse through unnecessary access.', pilar: 'Integrity', status: 'Active' },
  ],
  es: [
    { id: 'ART 00', title: 'Monetización Ética', desc: 'La monetización de datos personales está estrictamente prohibida. Los modelos de negocio deben estar desacoplados de la vigilancia.', pilar: 'Ética', status: 'Core Logic' },
    { id: 'ART 01', title: 'Privacy by Design', desc: 'La privacidad integrada en la arquitectura fundamental para minimizar la recolección de datos desde cero.', pilar: 'Arquitectura', status: 'Mandatory' },
    { id: 'ART 02', title: 'Security by Default', desc: 'Las configuraciones de seguridad más altas están activadas por defecto. La seguridad es el estado estándar.', pilar: 'Arquitectura', status: 'Mandatory' },
    { id: 'ART 03', title: 'Zero Trust', desc: 'Nunca confíes, siempre verifica. El acceso se otorga de forma granular y se valida continuamente.', pilar: 'Arquitectura', status: 'Active' },
    { id: 'ART 04', title: 'Zero Knowledge', desc: 'E2EE es obligatorio. Los proveedores deben ser estructuralmente incapaces de leer el contenido de las personas.', pilar: 'Soberanía', status: 'Enforced' },
    { id: 'ART 05', title: 'Cero Datos Personales', desc: 'No se almacenan datos PII más allá de la funcionalidad absoluta. Los sistemas no pueden perfilar a las personas.', pilar: 'Soberanía', status: 'Enforced' },
    { id: 'ART 06', title: 'Cero Registros de Actividad', desc: 'Sin registros de actividad, direcciones IP o metadatos utilizados para rastrear el comportamiento.', pilar: 'Soberanía', status: 'Enforced' },
    { id: 'ART 07', title: 'Open Source', desc: 'La transparencia es confianza. Todo el código debe estar abierto para auditoría pública.', pilar: 'Integridad', status: 'Public Audit' },
    { id: 'ART 08', title: 'Privilegio Mínimo', desc: 'Solo se solicitan los permisos esenciales. Sin posibilidad de abuso por acceso innecesario.', pilar: 'Integridad', status: 'Active' },
  ]
};
